# Generated by Django 4.2.19 on 2025-02-17 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicle",
            options={"verbose_name": "车辆信息"},
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="charging_time",
            field=models.IntegerField(verbose_name="充电时长"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="code",
            field=models.CharField(max_length=100, verbose_name="车辆编码"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="image",
            field=models.ImageField(upload_to="vehicles/", verbose_name="车辆图片"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="name",
            field=models.CharField(max_length=100, verbose_name="车辆名称"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="车主备注"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="所属用户",
            ),
        ),
    ]
