# Generated by Django 4.2.19 on 2025-02-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "vehicle",
            "0002_alter_vehicle_options_alter_vehicle_charging_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="note",
            field=models.TextField(blank=True, default="", verbose_name="车主备注"),
            preserve_default=False,
        ),
    ]
