# Generated by Django 4.2.19 on 2025-02-17 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="文件名"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="files/",
                        verbose_name="文件",
                    ),
                ),
                (
                    "ext",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="文件扩展名"
                    ),
                ),
                ("size", models.IntegerField(default=0, verbose_name="文件大小")),
                (
                    "type",
                    models.IntegerField(
                        choices=[(0, "未知"), (1, "简历"), (2, "作品"), (3, "管理员")],
                        default=0,
                        verbose_name="文件类型",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "文件",
                "verbose_name_plural": "文件",
                "db_table": "zq_file",
            },
        ),
        migrations.AddConstraint(
            model_name="file",
            constraint=models.CheckConstraint(
                check=models.Q(("type__in", [0, 1, 2, 3])),
                name="files_file_type_valid",
            ),
        ),
    ]
