# Generated by Django 4.2.19 on 2025-02-25 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vehicle", "0003_alter_vehicle_note"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MoveRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "move_time",
                    models.DateTimeField(auto_now=True, verbose_name="挪车时间"),
                ),
                (
                    "move_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="move_images/",
                        verbose_name="挪车图片",
                    ),
                ),
                (
                    "move_note",
                    models.TextField(blank=True, verbose_name="挪车备注"),
                ),
                (
                    "move_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="挪车用户",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="挪车用户",
                    ),
                ),
                (
                    "move_vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicle.vehicle",
                        verbose_name="被挪车辆",
                    ),
                ),
                (
                    "moved_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="被挪车用户",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="被挪车用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "挪车记录",
            },
        ),
    ]
