# Generated by Django 4.2.19 on 2025-02-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("move", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moverecord",
            name="is_initial",
            field=models.BooleanField(default=False, verbose_name="充电桩初始是否空闲"),
        ),
    ]
