# Generated by Django 4.2.19 on 2025-02-18 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="消息内容")),
                (
                    "send_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="发送时间"
                    ),
                ),
                (
                    "receive_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receive_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="接收者id",
                    ),
                ),
                (
                    "send_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="send_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发送者id",
                    ),
                ),
            ],
            options={
                "verbose_name": "消息",
                "verbose_name_plural": "消息列表",
                "ordering": ["-send_time"],
            },
        ),
    ]
