# Generated by Django 4.2.19 on 2025-02-20 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifications",
            name="read_status",
            field=models.CharField(
                choices=[("unread", "Unread"), ("read", "Read")],
                default="unread",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="receive_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receive_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="接收者",
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="send_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="send_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="发送者",
            ),
        ),
    ]
