# Generated by Django 4.2.19 on 2025-02-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_notifications_read_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifications",
            name="read_status",
            field=models.CharField(
                choices=[("unread", "Unread"), ("read", "Read")],
                default="unread",
                max_length=10,
                verbose_name="已读状态",
            ),
        ),
    ]
