version: "3.8"
name: zq_yifu_backend

x-django: &django
  image: registry-vpc.cn-hangzhou.aliyuncs.com/ziqiang_studio/yifu:django
  env_file: ./.env # ENV file
  depends_on:
    - redis
  networks:
    - app-net

services:
  ### Caddy container #########################################
  caddy:
    image: registry-vpc.cn-hangzhou.aliyuncs.com/ziqiang_studio/caddy:latest
    depends_on:
      - django
    networks:
      - app-net
      - traefik
    labels:
      traefik.enable: true
      traefik.http.routers.template.rule: Host(`api.yifu.ziqiang.net.cn`)
      traefik.http.routers.template.entrypoints: websecure
      traefik.http.services.template.loadbalancer.server.port: 80

  ### Redis container ##########################################
  redis:
    image: registry-vpc.cn-hangzhou.aliyuncs.com/ziqiang_studio/redis:latest
    networks:
      - app-net

  ### Django container #########################################
  django:
    <<: *django
    volumes:
      - ./log:/app/logs:rw

### Add Network Bridge info #########################################
networks:
  app-net: {}
  traefik:
    external: true
