# Generated by Django 4.2.19 on 2025-02-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_url",
            field=models.TextField(
                blank=True, max_length=100, verbose_name="头像路径"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="credit_score",
            field=models.IntegerField(default=100, verbose_name="信用分"),
        ),
        migrations.AddField(
            model_name="user",
            name="faculty",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="学部"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                blank=True, default="昵称", max_length=64, verbose_name="昵称"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatar/", verbose_name="头像"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="手机号"
            ),
        ),
    ]
