# Generated by Django 4.2.19 on 2025-02-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "users",
            "0002_user_avatar_url_user_credit_score_user_faculty_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar_url",
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                blank=True, default="新用户", max_length=64, verbose_name="昵称"
            ),
        ),
    ]
