# Generated by Django 4.2.19 on 2025-02-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_user_avatar_url_alter_user_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("idle", "空闲中"),
                    ("queuing", "排队中"),
                    ("assigned", "已分配充电桩"),
                    ("charging", "充电中"),
                    ("waiting", "充电完毕等待挪车"),
                    ("moved", "已被挪车"),
                ],
                default="idle",
                max_length=20,
                verbose_name="用户状态",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="update_time",
            field=models.DateTimeField(auto_now=True, verbose_name="状态更新时间"),
        ),
    ]
